spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering.
    #Explicitly configure spring.jpa.open-in-view to disable this warning.
    open-in-view: false